const listItems = [
    {
        //  *********** CATEGORIA MATES ***********
        id: 1,
        title : 'Automate',
        description : "",
        options: [],
        price : 2400,
        category:"mates",
        quantity: 1,
        urlImg: 'automate',
        urlImgFrag: '',
    },
    {
        id: 2,
        title : 'Mate Pampa',
        description : "",
        options: ["Boca Abierta Negro", "Boca Abierta Blanco", "Boca Abierta Beige", 
                "Boca Abierta Lila", "Boca Abierta Rojo", "Boca Abierta Rosa", 
                "Boca Abierta Verde Manzana", "Boca Abierta Verde Oliva",
                "Boca Cerrada Negro", "Boca Cerrada Blanco", "Boca Cerrada Beige", 
                "Boca Cerrada Lila", "Boca Cerrada Rojo", "Boca Cerrada Rosa", 
                "Boca Cerrada Verde Manzana", "Boca Cerrada Verde Oliva"],
        price : 2900,
        category:"mates",
        quantity: 1,
        urlImg: 'matepampa',
        urlImgFrag: '',
    },
    {
        id: 3,
        title : 'Maderate',
        description : "",
        options: ["Negro", "Blanco", "Rosa","Beige", "Lila","Gris","Celeste","Verde Manzana", "Verde Oliva"],
        price : 2350,
        category:"mates",
        quantity: 1,
        urlImg: 'maderate',
        urlImgFrag: '',
    },
    {
        id: 4,
        title : 'Matérmico',
        description : "",
        options: ["Rojo","Negro","Blanco", "Verde", "Rosa", "Azul", "Beige","Argentina"],
        price : 1500,
        category:"mates",
        quantity: 1,
        urlImg: 'matermico',
        urlImgFrag: '',
    },
    {
        id: 5,
        title : 'Mateava',
        description : "",
        options: ["Negro", "Blanco", "Rosa","Beige", "Lila","Gris","Celeste","Verde Manzana", "Verde Oliva"],
        price : 1100,
        category:"mates",
        quantity: 1,
        urlImg: 'mateava',
        urlImgFrag: '',
    },
    {
        id: 6,
        title : 'Mate Deco',
        description : "",
        options: [],
        price : 950,
        category:"mates",
        quantity: 1,
        urlImg: 'matedeco',
        urlImgFrag: '',
    },
    
    // *********** CATEGORIA REGALOS ***********
    {
        id: 7,
        title : 'Kit Aromas',
        description : "",
        options: [],
        price : 1500,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitaromas',
        urlImgFrag: '',
    },
    {
        id: 8,
        title : 'Kit Aromático',
        description : "",
        options: [],
        price : 1600,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitaromatico',
        urlImgFrag: '',
    },
    {
        id: 9,
        title : 'Kit Deco',
        description : "",
        options: [],
        price : 3600,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitdeco',
        urlImgFrag: '',
    },
    {
        id: 10,
        title : 'Kit Energía',
        description : "",
        options: [],
        price : 600,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitenergia',
        urlImgFrag: '',
    },
    {
        id: 11,
        title : 'Kit Facial',
        description : "",
        options: [],
        price : 2600,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitfacial',
        urlImgFrag: '',
    },
    {
        id: 12,
        title : 'Kit Facial Completo',
        description : "",
        options: [],
        price : 6500,
        category:"regalos",
        quantity: 1,
        urlImg: 'kittfacialcompleto',
        urlImgFrag: '',
    },
    {
        id: 13,
        title : 'Kit Mini',
        description : "",
        options: [],
        price : 300,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitmini',
        urlImgFrag: '',
    },
    {
        id: 14,
        title : 'Kit Relax',
        description : "",
        options: [],
        price : 2400,
        category:"regalos",
        quantity: 1,
        urlImg: 'kitrelax',
        urlImgFrag: '',
    },

    // *********** CATEGORIA DECO ***********
    {
        id: 15,
        title : 'Budhas de la Meditación',
        description : "",
        options: ["Bronce", "Plata"],
        price : 2400,
        category:"decoracion",
        quantity: 1,
        urlImg: 'budhasmed',
        urlImgFrag: '',
    },
    {
        id: 16,
        title : 'Budhas Mini',
        description : "",
        options: ["Amarillo", "Rojo", "Lila", "Blanco", "Naranja", "Rosa", "Verde", "Celeste"],
        price : 1100,
        category:"decoracion",
        quantity: 1,
        urlImg: 'budhasmini',
        urlImgFrag: '',
    },
    {
        id: 17,
        title : 'Cascada',
        description : "",
        options: [],
        price : 900,
        category:"decoracion",
        quantity: 1,
        urlImg: 'cascada',
        urlImgFrag: '',
    },
    {
        id: 18,
        title : 'Hornillo Corazón',
        description : "",
        options: ["Rosa", "Blanco", "Rojo"],
        price : 1450,
        category:"decoracion",
        quantity: 1,
        urlImg: 'hornocoraz',
        urlImgFrag: '',
    },
    {
        id: 19,
        title : 'Hornillo Elefante',
        description : "",
        options: ["Negro", "Gris", "Blanco"],
        price : 1280,
        category:"decoracion",
        quantity: 1,
        urlImg: 'hornoelef',
        urlImgFrag: '',
    },
    {
        id: 20,
        title : 'Hornillo Hindú',
        description : "",
        options: ["Budha", "Elefante Ganesh"],
        price : 800,
        category:"decoracion",
        quantity: 1,
        urlImg: 'hornohindu',
        urlImgFrag: '',
    },
    {
        id: 21,
        title : 'Hornillo Pétalos',
        description : "",
        options: ["Blanco", "Gris", "Negro"],
        price : 800,
        category:"decoracion",
        quantity: 1,
        urlImg: 'hornopetalos',
        urlImgFrag: '',
    },
    {
        id: 22,
        title : 'Hornillo Rombo',
        description : "",
        options: ["Blanco", "Gris", "Marrón"],
        price : 860,
        category:"decoracion",
        quantity: 1,
        urlImg: 'hornorombo',
        urlImgFrag: '',
    },
    {
        id: 23,
        title : 'Lámpara Budha',
        description : "",
        options: ["No Veo", "No Escucho", "No Hablo"],
        price : 4800,
        category:"decoracion",
        quantity: 1,
        urlImg: 'lampbudha',
        urlImgFrag: '',
    },
    {
        id: 24,
        title : 'Lámpara Fenshui',
        description : "",
        options: ["Plata", "Bronce"],
        price : 4800,
        category:"decoracion",
        quantity: 1,
        urlImg: 'lampfenshui',
        urlImgFrag: '',
    },

    // *********** CATEGORIA ILUMINARTE ***********
    {
        id: 25,
        title : 'Conos x 10',
        description : "",
        options: ["Champa","Energia Limpia","Esencias de la India","Frutilla",
                "Lavanda","Mango","Mil Flores","Palo Santo","Jazmín","Rosa",
                "Sándalo","Vainilla"],
        price : 160,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'conos',
        urlImgFrag: '',
    },
    {
        id: 26,
        title : 'Sahumerios x 20',
        description : "",
        options: [],
        price : 300,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'sahum',
        urlImgFrag: '',
    },
    {
        id: 27,
        title : 'Vela Mandala',
        description : "",
        options: ["Lavanda Francesa","Jazmín y Bamboo","Vainilla Africana"],
        price : 1000,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velamandala',
        urlImgFrag: '',
    },
    {
        id: 28,
        title : 'Velitas Blancas x 24',
        description : "",
        options: [],
        price : 1250,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velasblancas',
        urlImgFrag: '',
    },
    {
        id: 29,
        title : 'Velitas Colores x 12',
        description : "",
        options: ["Blancas","Rojas","Naranjas","Rosas","Azules","Violetas"],
        price : 480,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velascolor',
        urlImgFrag: '',
    },
    {
        id: 30,
        title : 'Vela de Soja',
        description : "",
        options: [],
        price : 1200,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velasoja',
        urlImgFrag: '',
    },
    {
        id: 31,
        title : 'Velitas Aromáticas x12 ',
        description : "",
        options: ["Citronela","Chocolate","Esencias de la India","Frutilla",
                "Lavanda","Jazmín","Limón","Mango","Maracuyá","Pimpollo de Rosas",
                "Pomelo Naranja","Vainilla","Violeta"],
        price : 700,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velitasarom',
        urlImgFrag: '',
    },
    {
        id: 32,
        title : 'Velitas de Soja',
        description : "",
        options: [],
        price : 550,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'velitasoja',
        urlImgFrag: '',
    },
    {
        id: 33,
        title : 'Veloncitos',
        description : "",
        options: ["Citronela","Champa","Esencias de la India","Frutilla", "Flores de Violetas",
                "Lavanda","Jazmín","Limón","Sándalo","Mango y Maracuyá","Pimpollo de Rosas",
                "Palo santo","Pomelo Naranja","Vainilla","Violeta", "Incienso"],
        price : 260,
        category:"iluminarte",
        quantity: 1,
        urlImg: 'veloncitos',
        urlImgFrag: '',
    },

     // *********** CATEGORIA MILANO ***********
    {
        id: 34,
        title : 'Agua Micelar',
        description : "",
        options: [],
        price : 1300,
        category:"milano",
        quantity: 1,
        urlImg: 'aguamic',
        urlImgFrag: '',
    },
    {
        id: 35,
        title : 'Body Splash',
        description : "",
        options: ["Captivant","Flowers","Funny Girl","Miami Summer", 
                "Pure Seduction","Romantic Venice"],
        price : 950,
        category:"milano",
        quantity: 1,
        urlImg: 'bodysplash',
        urlImgFrag: '',
    },
    {
        id: 36,
        title : 'Crema Humectante',
        description : "",
        options: ["Captivant","Flowers","Funny Girl","Miami Summer", 
                "Pure Seduction","Romantic Venice"],
        price : 770,
        category:"milano",
        quantity: 1,
        urlImg: 'crema',
        urlImgFrag: '',
    },
    {
        id: 37,
        title : 'Jabón Líquido',
        description : "",
        options: ["Relax","Damasco","Cítrico","Cremoso","Coco","Manzana"],
        price : 450,
        category:"milano",
        quantity: 1,
        urlImg: 'jabon',
        urlImgFrag: '',
    },
    {
        id: 38,
        title : 'Perfumes',
        description : "",
        options: ["HOMBRE - Carolina Herrera Classic", "HOMBRE - One Million", "HOMBRE - Invicto", 
                "HOMBRE - Polo", "HOMBRE - Wanted", "HOMBRE - CoolWater", "HOMBRE - Farenheit",
                "HOMBRE - Le Male", "HOMBRE - Pure XS", "HOMBRE - BD Body", "HOMBRE - Y",
                "MUJER - Amor Amor","MUJER - Carolina Herrera 212", "MUJER - One", "MUJER - Red Door",
                "MUJER - Flowers","MUJER - Good Girl", "MUJER - La Vida es Bella","MUJER - Olimpic",
                "MUJER - Olympea", "MUJER - Light Blue ","MUJER - Lady Million", "MUJER - J adore",
                "MUJER - Chanel N° 5","MUJER - Bella", "MUJER - Si","MUJER - Pure XS", "MUJER - BLK OP"],
        price : 1800,
        category:"milano",
        quantity: 1,
        urlImg: 'perfume',
        urlImgFrag: '',
    },
    {
        id: 39,
        title : 'Perfumes Mini',
        description : "",
        options: ["HOMBRE - Carolina Herrera Classic", "HOMBRE - One Million", "HOMBRE - Invicto", 
                "HOMBRE - Polo", "HOMBRE - Wanted", "MUJER - Amor Amor","MUJER - Carolina Herrera 212",
                "MUJER - Flowers","MUJER - Good Girl", "MUJER - La Vida es Bella","MUJER - Olimpic"],
        price : 800,
        category:"milano",
        quantity: 1,
        urlImg: '/miniperf',
        urlImgFrag: '',
    },

    // *********** CATEGORIA SAPHIRUS ***********
    {
        id: 40,
        title : 'Esencias Ambar',
        description : "",
        options: ["Amber", "Bamboo", "Cinamon","Citronella", "Coco Vai","Eucaliptus", "Flores Blancas",
                    "Green", "Incienso", "Jazmín","Lavanda","Limón", "Linah","Manzana Canela", 
                    "Miel Limón", "Mirra","Musk", "Nag Champa", "Naranja Pimienta", "New Delhi", 
                    "Orange","Oriente", "Palo Santo", "Papaya", "Patchouly", "Sándalo", "Vainilla",
                    "Vrindavan" ],
        price : 250,
        category:"saphirus",
        quantity: 1,
        urlImg: 'aceitea',
        urlImgFrag: '',
    },
    {
        id: 41,
        title : 'Aerosoles Ambar',
        description : "",
        options: ["Amour","Antitabaco","Bamboo","Bebé","Chicle","Citrus",
                "Coco Vai","Cony","Daniel","Flores Blancas","Flowers","Hawai",
                "Indiana","Invicto","Jazmín","Lavanda","Limón","Linah","Lola",
                "Magnolia y Fresias","Mery","Orange","Papaya","Patio","Rocío",
                "Té Verde", "Tokyo","Tropical","Uva","Vainilla"],
        price : 520,
        category:"saphirus",
        quantity: 1,
        urlImg: 'aerosola',
        urlImgFrag: '',
    },
    {
        id: 42,
        title : 'Aerosoles',
        description : "",
        options: ["Apple", "Chicle","Coco Vai", "Damasco", "Guaraná", 
                "Hawai", "Coco Maracuyá", "Melón", "Papaya", "Peras y Flores",
                "Sweet", "Tropical", "Uva", "Limón Dulce y Vainilla","Olimpic",
                "Marino", "Oriente", "Cappuccino","Dolce", "Green", "Lady","Mito",
                "Manzana Canela", "Naranja Pimienta", "París", "Praga","New York",
                "Bamboo", "Citronella", "Flores Blancas", "Jazmín", "Jazz","Palace",
                "Lavanda", "Lola", "Magnolia y Fresias", "Palo Santo", "Rocío",
                "Vainilla", "Violetas","Citrus", "Limón", "Linah", "London", "Pacific",
                "Miel y Limón", "Orange", "Pink", "Verbena", "Amour", "Bebé","Etiqueta",
                "Cony", "Cristóbal", "Flowers", "Indiana", "Mery", "Nina","Duvet","Faren",
                "Paula", "Tokyo","Frutilla","Maracuyá","Mix Tropical","Fantasía", "Mystic",
                "Antitabaco", "Breeze","Fresh","Rosas","Tilo","Mandarina", "Blue","Apolo",
                "Angel","Invicto","Daniel","One Million", "Patio", "Pitanga","Prunella",
                "Sandia y Pepino", "Lavanda y Té Verde", "Bergamota y Naranja", "Pera y Durazno",
                "Naranja y Chocolate", "Cafe y Chocolate","Vainilla Tonka", "Pomelo Rosado", "Ciruela",
                "Bouquet Floral"],
        price : 650,
        category:"saphirus",
        quantity: 1,
        urlImg: 'aerosols',
        urlImgFrag: '',
    },
    {
        id: 44,
        title : 'Air Cool',
        description : "",
        options:  ["Chicle","Coco","Frutos Rojos","Manzana Verde","Uva","Bamboo",
                "Flores Blancas","Lavanda","Rocío","Vainilla","Limón","Acqua"],
        price : 630,
        category:"saphirus",
        quantity: 1,
        urlImg: 'aircool',
        urlImgFrag: '',
    },
    {
        id: 45,
        title : 'Caritas',
        description : "",
        options:  ["Manzana","Multifruta","Aqua","Lima Limón","Caribe", "Sport"],
        price : 420,
        category:"saphirus",
        quantity: 1,
        urlImg: 'caritas',
        urlImgFrag: '',
    },
    {
        id: 46,
        title : 'Difusores Premium',
        description : "",
        options: ["Frutos Patagónicos","Vainilla y Coco", "Canela de Ceylán","Bergamota Nature", 
                "Caramel Jam","Flores Blancas","Jazmín Bouquet","Lavanda y Romero","Cokies and Cream",
                "Pétalos de Orquídeas","Vainilla Oriental","Lemon Peel", "Naranja y Limón","Melocotón Blanco", 
                "Sweet Baby", "Geranio y Frutos Tropicales", "Frutos Tropicales", "Moras y Naranjas", "Eucalipto y Menta"],
        price : 1700,
        category:"saphirus",
        quantity: 1,
        urlImg: 'difuprem',
        urlImgFrag: '',
    },
    {
        id: 47,
        title : 'Difusores',
        description : "",
        options: ["Apple", "Chicle","Coco Vai", "Damasco", "Guaraná", 
                "Hawai", "Maracuyá", "Melón", "Papaya", "Peras y Flores",
                "Sweet", "Tropical", "Uva", "Limón Dulce y Vainilla",
                "Marino", "Oriente", "Cappuccino","Dolce", "Green",
                "Manzana Canela", "Naranja Pimienta", "París", "Praga",
                "Bamboo", "Citronella", "Flores Blancas", "Jazmín", "Jazz",
                "Lavanda", "Lola", "Magnolia y Fresias", "Palo Santo", "Rocío",
                "Vainilla", "Violetas","Citrus", "Limón", "Linah", "London",
                "Miel y Limón", "Orange", "Pink", "Verbena", "Amour", "Bebé",
                "Cony", "Cristóbal", "Flowers", "Indiana", "Mery", "Nina",
                "Paula", "Tokyo","Patio", "Naranja y Chocolate", "Café y Chocolate",
                "Lavanda y Té Verde", "Vainilla Tonka", "Pomelo Rosado", "Pera y Durazno",
                "Adventure", "Invicto", "Wanted", "Bella"],
        price : 670,
        category:"saphirus",
        quantity: 1,
        urlImg: 'difusor',
        urlImgFrag: '',
    },
    {
        id: 48,
        title : 'Equipos',
        description : "",
        options: ["Blanco", "Negro", "Beige", "Bordo"],
        price : 2100,
        category:"saphirus",
        quantity: 1,
        urlImg: 'equipo',
        urlImgFrag: '',
    },
    {
        id: 49,
        title : 'Esencias',
        description : "",
        options: ["Amber", "Bamboo", "Cinamon","Citronella", "Coco Vai","Eucaliptus", "Flores Blancas",
                "Green", "Incienso", "Jazmín","Lavanda","Limón", "Linah","Manzana Canela", 
                "Miel Limón", "Mirra","Musk", "Nag Champa", "Naranja Pimienta", "New Delhi", 
                "Orange","Oriente", "Palo Santo", "Papaya", "Patchouly", "Sándalo", "Vainilla",
                "Vrindavan" ],
        price : 380,
        category:"saphirus",
        quantity: 1,
        urlImg: 'esencias',
        urlImgFrag: '',
    },
    {
        id: 50,
        title : 'Home Spray',
        description : "",
        options: ["Apple Champagne", "Arandanos y Canela","Coco Maracuyá","Mix Tropical", 
                "Sandia Pepino", "Uva y Arandanos", "Vainilla Cream", "Breeze",
                "Sweet Flowers","Fancy Dreams","Citric Wood", "Lima Limón", "Flor de Loto",
                "Naranja Pomelo","Mango Anana","Groselias y Nectarina", "Clean Cotton",
                "Pomelo y Menta", "Amapola y Cerezos","Clementina y Flores Blancas",
                "Montain Water", "Fresias y Bergamota"],
        price : 880,
        category:"saphirus",
        quantity: 1,
        urlImg: 'home',
        urlImgFrag: '',
    },
    {
        id: 51,
        title : 'Hornillos',
        description : "",
        options: ["Arena", "Blanco"],
        price : 880,
        category:"saphirus",
        quantity: 1,
        urlImg: 'hornillos',
        urlImgFrag: '',
    },
    {
        id: 52,
        title : 'Latitas',
        description : "",
        options: ["Chicle","Coco","Frutos Rojos","Manzana Verde","Uva","Bamboo",
                "Flores Blancas","Lavanda","Rocío","Vainilla","Limón","Acqua"],
        price : 1150,
        category:"saphirus",
        quantity: 1,
        urlImg: 'latitas',
        urlImgFrag: '',
    },
    {
        id: 53,
        title : 'Minis',
        description : "",
        options: ["Chicle","Coco Vai", "Bella","Hawai","Papaya","Pitanga","Cereza Malbec",
                "Tropical", "Uva","Marino", "Oriente", "Olimpyc", "Green","Antitabaco",
                "Bamboo", "Flores Blancas","Lavanda", "Lola", "Magnolia y Fresias", "Vainilla",
                "Rocío","Citrus", "Limón", "Linah","Verbena", "Amour", "Bebé", "Male",
                "Cony","Flowers","Mery","Paula","Angel","Invicto","One Million","Wanted"],
        price : 360,
        category:"saphirus",
        quantity: 1,
        urlImg: 'minis',
        urlImgFrag: '',
    },
    {
        id: 54,
        title : 'Route',
        description : "",
        options: ["Frutos Rojos", "Manzana", "Tropical","Tutti Frutti",
                "Marino","Cítrico","Naranja", "Polo","Naranja Frutilla", "Uva"],
        price : 420,
        category:"saphirus",
        quantity: 1,
        urlImg: 'route',
        urlImgFrag: '',
    },
    {
        id: 55,
        title : 'Sensaciones',
        description : "",
        options: ["Brisa Marina", "Bosque de Pino", "Floral","Lavanda",
                "Vainilla", "Cítrico","Orange","Aqua Rosé"],
        price : 490,
        category:"saphirus",
        quantity: 1,
        urlImg: 'sensaciones',
        urlImgFrag: '',
    },
    {
        id: 56,
        title : 'Tarjetas',
        description : "",
        options: ["Cereza Malbec", "Frutos Rojos", "Magnolias y Vainilla", "Lavanda y Manzanilla",
                    "Lima y Menta", "Rosa y Neroli"],
        price : 800,
        category:"saphirus",
        quantity: 1,
        urlImg: 'tarjetas',
        urlImgFrag: '',
    },
    {
        id: 57,
        title : 'Textiles Ambar',
        description : "",
        options: [ "Chicle","Coco Vai", "Bella","Hawai","Papaya", "Jazmín",
                    "Tropical", "Uva", "Olimpyc", "Green", "Nina",
                    "Bamboo", "Flores Blancas","Lavanda", "Lola", "Magnolia y Fresias", "Vainilla",
                    "Rocío", "Limón", "Linah","Amour", "Bebé",
                    "Cony","Flowers","Mery","Paula","Angel","Invicto","One Million","Wanted"],
        price : 310,
        category:"saphirus",
        quantity: 1,
        urlImg: 'textila',
        urlImgFrag: '',
    },
    {
        id: 58,
        title : 'Textiles',
        description : "",
        options: ["Apple", "Chicle","Coco Vai", "Bella", "Guaraná", 
                "Hawai", "Coco Maracuyá", "Man", "Papaya", "Pitanga", "Sweet Flowers",
                "Lady", "Tropical", "Uva", "Limón Dulce y Vainilla", "Sandia Pepino",
                "Marino", "Oriente", "Olimpyc","Duvet", "Green", "Uva y Arándanos",
                "Beauty", "Naranja Pimienta","Bamboo", "Flores Blancas", "Jazmín",
                "Lavanda", "Lola", "Magnolia y Fresias", "Apolo", "Rocío", "XS",
                "Violetas","Citrus", "Limón", "Linah","Pink", "Verbena", "Amour", "Bebé",
                "Cony", "Cristóbal", "Flowers", "Indiana", "Mery", "Nina", "Mis Tropical",
                "Paula", "Tokyo","Antitabaco","Rosas", "Blue", "Brezze", "Lima Limón",
                "Angel","Invicto","Daniel","One Million", "Patio","Polo","Wanted",
                "Adventure", "Bad Man", "Cereza Malbec", "Opium", "Pomelo Rosado"],
        price : 470,
        category:"saphirus",
        quantity: 1,
        urlImg: 'textils',
        urlImgFrag: '',
    },
    // *********** CATEGORIA SAGRADA MADRE ***********
    {
        id: 59,
        title : 'Bombitas 7 Chacras',
        description : "",
        options: [],
        price : 380,
        category:"sagrada",
        quantity: 1,
        urlImg: 'bomb7chacras',
        urlImgFrag: '',
    },
    {
        id: 60,
        title : 'Bombitas',
        description : "",
        options: ["Atrae Dinero","Defumación Completa", "Destrabe","Palo Santo",
                "7 Hierbas Copal", "7 Poderes","Abre Caminos","Limpieza Energética"],
        price : 200,
        category:"sagrada",
        quantity: 1,
        urlImg: 'bombitas',
        urlImgFrag: '',
    },
    {
        id: 61,
        title : 'Carbón Defumador',
        description : "",
        options: [],
        price : 40,
        category:"sagrada",
        quantity: 1,
        urlImg: 'carbondef',
        urlImgFrag: '',
    },
    {
        id: 62,
        title : 'Cuenco Sahumador',
        description : "",
        options: [],
        price : 420,
        category:"sagrada",
        quantity: 1,
        urlImg: 'cuenco',
        urlImgFrag: '',
    },
    {
        id: 63,
        title : 'Perlas',
        description : "",
        options: ["Coco", "FLores Blancas", "Frutilla", "Jazmín", "Hindú",
                    "Lavanda", "Limón", "Primavera", "Reina de la Noche", 
                    "Rosas", "Sándalo", "Vainilla"],
        price : 310,
        category:"sagrada",
        quantity: 1,
        urlImg: 'perlas',
        urlImgFrag: '',
    },
    {
        id: 64,
        title : 'Sahumerios Ecologicos',
        description : "",
        options: ["Palo Santo con Copal","Palo Santo con Champa", "Palo Santo con Incienso",
                "Palo Santo con Jazmín","Palo Santo con Lavanda", "Palo Santo con Mirra",
                "Palo Santo","Palo Santo con Romero", "Palo Santo con Rosa",
                "Palo Santo con Sándalo","Palo Santo con Vainilla", "Palo Santo con Yagra",],
        price : 370,
        category:"sagrada",
        quantity: 1,
        urlImg: 'sahumeco',
        urlImgFrag: '',
    },
    {
        id: 65,
        title : 'Sahumerios Hierba',
        description : "",
        options: ["Anís Canela y Olíbano", "Eucalipto Laurel y Cedro", "Caléndula Manzanilla y Olíbano",
                "Lavanda y Olíbano", "Incienso Blanco", "Salvia Blanca", "Rosas y Olíbano"],
        price : 390,
        category:"sagrada",
        quantity: 1,
        urlImg: 'sahumhierba',
        urlImgFrag: '',
    },
    {
        id: 66,
        title : 'Sahumitos',
        description : "",
        options: ["Canela", "Estoraque y Alcanfor", "Mirra y Palo Santo", "Naranja y Citronella",
                    "Palo Santo", "Romero", "Rosas", "Ruda", "Sándalo", "Yagra"],
        price : 300,
        category:"sagrada",
        quantity: 1,
        urlImg: 'sahumitos',
        urlImgFrag: '',
    },
    {
        id: 67,
        title : 'Sahumerios Naturales',
        description : "",
        options: ["Mirra", "Citronella Naranja y Palo Santo", "Copal", "Incienso", "Romero y Ruda",
                    "Sándalo", "Yagra", "Flores", "Lavanda", "Limpieza Energetica", "Mirra y Palo Santo",
                    "Romero y Aromáticas", "Sándalo  y Aromáticas" ],
        price : 380,
        category:"sagrada",
        quantity: 1,
        urlImg: 'sahumnat',
        urlImgFrag: '',
    },
    // *********** CATEGORIA REMERAS ***********
    {
        id: 68,
        title : 'Blusa Floral (L)',
        description : "",
        options: [ ],
        price : 1900,
        category:"remeras",
        quantity: 1,
        urlImg: 'blusafloral',
        urlImgFrag: '',
    },
    {
        id: 69,
        title : 'Amabilidad ML (XXXL)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remerasamab',
        urlImgFrag: '',
    },
    {
        id: 70,
        title : 'Amabilidad MC (S)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraamabilidad',
        urlImgFrag: '',
    },
    {
        id: 71,
        title : 'Amor MC (M)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraamor',
        urlImgFrag: '',
    },
    {
        id: 72,
        title : 'Cartas ML (XXL)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeracartas',
        urlImgFrag: '',
    },
    {
        id: 73,
        title : 'Corazones ML (M)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeracorazones',
        urlImgFrag: '',
    },
    {
        id: 74,
        title : 'Flores MC (M)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraflores',
        urlImgFrag: '',
    },
    {
        id: 75,
        title : 'Mirar ML (XXL)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeramirar',
        urlImgFrag: '',
    },
    {
        id: 76,
        title : 'Moon ML (XL)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeramoon',
        urlImgFrag: '',
    },
    {
        id: 77,
        title : 'Ojitos ML (L)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraojitos',
        urlImgFrag: '',
    },
    {
        id: 78,
        title : 'Ojitos MC (M)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraojos',
        urlImgFrag: '',
    },
    {
        id: 79,
        title : 'Osito MC (M)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraosito',
        urlImgFrag: '',
    },
    {
        id: 80,
        title : 'Protección ML (L)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeraproteccion',
        urlImgFrag: '',
    },
    {
        id: 81,
        title : 'Vibra Alto MC (M)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeravibraalto',
        urlImgFrag: '',
    },
    {
        id: 82,
        title : 'Vuela Alto 3/4 (M)',
        description : "",
        options: [ ],
        price : 1200,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeravuelaalto',
        urlImgFrag: '',
    },
    {
        id: 83,
        title : 'Yin-Yang ML (XXXL)',
        description : "",
        options: [ ],
        price : 2300,
        category:"remeras",
        quantity: 1,
        urlImg: 'remerayinyang',
        urlImgFrag: '',
    },
    {
        id: 84,
        title : 'Love MC (XXXL)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeronlove',
        urlImgFrag: '',
    },
    {
        id: 85,
        title : 'Rolling MC (XXXL)',
        description : "",
        options: [ ],
        price : 1000,
        category:"remeras",
        quantity: 1,
        urlImg: 'remeronrolling',
        urlImgFrag: '',
    },
]

export default listItems