const listItems = [
    {
        id: 1,
        title : 'Textil',
        description : "",
        options: ["frag1", "frag2"],
        price : 290,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/automate.jpg',
        urlImgFrag: '/assets/productos/mates/maderate.jpg',
    },
    {
        id: 2,
        title : 'Difusor',
        description : "",
        options: ["frag1", "frag2"],
        price : 850,
        category:"saphirus",
        quantity: 1,
        urlImg: 'https://saphirus.com.ar/wp-content/uploads/2022/04/difusor-premium-lavanda-y-romero-01-016-800x800.jpg',
        urlImgFrag: '/assets/productos/mates/maderate.jpg',
    },
    {
        id: 3,
        title : 'Air Cool',
        description : "",
        options: [],
        price : 360,
        category:"mates",
        quantity: 1,
        urlImg: 'https://saphirus.com.ar/wp-content/uploads/2022/04/1ovA3O26hl4h9iFMgkZjhLNa5S9eYMqLJccmzS4U-1-800x800.jpeg',
        urlImgFrag: '/assets/productos/mates/maderate.jpg',
    },
    {
        id: 4,
        title : 'Equipo',
        description : "",
        options: [],
        price : 1300,
        category:"mates",
        quantity: 1,
        urlImg: 'https://saphirus.com.ar/wp-content/uploads/2022/04/Red-Blood-430x430.png',
        urlImgFrag: '/assets/productos/mates/maderate.jpg',
    },
    {
        id: 5,
        title : 'Titulo',
        description : "Prueba de img con error",
        options: [],
        price : 500,
        category:"mates",
        quantity: 1,
        urlImg: '/img-not-found.png',
        urlImgFrag: '/assets/productos/mates/maderate.jpg',
    },  
]

export default listItems