const listItems = [
    {
        //  *********** CATEGORIA MATES ***********
        id: 1,
        title : 'Automate',
        description : "",
        options: [],
        price : 2300,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/automate.jpg',
        urlImgFrag: '',
    },
    {
        id: 2,
        title : 'Mate Pampa',
        description : "",
        options: ["Boca Abierta Negro", "Boca Abierta Blanco", "Boca Abierta Beige", 
                "Boca Abierta Lila", "Boca Abierta Rojo", "Boca Abierta Rosa", 
                "Boca Abierta Verde Manzana", "Boca Abierta Verde Oliva",
                "Boca Cerrada Negro", "Boca Cerrada Blanco", "Boca Cerrada Beige", 
                "Boca Cerrada Lila", "Boca Cerrada Rojo", "Boca Cerrada Rosa", 
                "Boca Cerrada Verde Manzana", "Boca Cerrada Verde Oliva"],
        price : 2600,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/matepampa.jpg',
        urlImgFrag: '',
    },
    {
        id: 3,
        title : 'Maderate',
        description : "",
        options: ["Negro", "Blanco", "Rosa","Beige", "Lila","Gris","Celeste","Verde Manzana", "Verde Oliva"],
        price : 2300,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/maderate.jpg',
        urlImgFrag: '',
    },
    {
        id: 4,
        title : 'Matérmico',
        description : "",
        options: ["Rojo","Negro","Blanco", "Verde", "Rosa", "Azul", "Beige","Argentina"],
        price : 1500,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/matermico.jpg',
        urlImgFrag: '',
    },
    {
        id: 5,
        title : 'Mateava',
        description : "",
        options: ["Negro", "Blanco", "Rosa","Beige", "Lila","Gris","Celeste","Verde Manzana", "Verde Oliva"],
        price : 1100,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/mateava.jpg',
        urlImgFrag: '',
    },
    {
        id: 6,
        title : 'Mate Deco',
        description : "",
        options: [],
        price : 950,
        category:"mates",
        quantity: 1,
        urlImg: '/assets/productos/mates/matedeco.jpg',
        urlImgFrag: '',
    },
    
    // *********** CATEGORIA REGALOS ***********
    {
        id: 7,
        title : 'Kit Aromas',
        description : "",
        options: [],
        price : 1400,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitaromas.jpg',
        urlImgFrag: '',
    },
    {
        id: 8,
        title : 'Kit Aromáticos',
        description : "",
        options: [],
        price : 1550,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitaromatico.jpg',
        urlImgFrag: '',
    },
    {
        id: 9,
        title : 'Kit Deco',
        description : "",
        options: [],
        price : 3550,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitdeco.jpg',
        urlImgFrag: '',
    },
    {
        id: 10,
        title : 'Kit Energía',
        description : "",
        options: [],
        price : 600,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitenergia.jpg',
        urlImgFrag: '',
    },
    {
        id: 11,
        title : 'Kit Facial',
        description : "",
        options: [],
        price : 2400,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitfacial.jpg',
        urlImgFrag: '',
    },
    {
        id: 12,
        title : 'Kit Facial Completo',
        description : "",
        options: [],
        price : 6500,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitfacialcompleto.jpg',
        urlImgFrag: '',
    },
    {
        id: 13,
        title : 'Kit Mini',
        description : "",
        options: [],
        price : 300,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitmini.jpg',
        urlImgFrag: '',
    },
    {
        id: 14,
        title : 'Kit Relax',
        description : "",
        options: [],
        price : 2350,
        category:"regalos",
        quantity: 1,
        urlImg: '/assets/productos/regalos/kitrelax.jpg',
        urlImgFrag: '',
    },

    // *********** CATEGORIA DECO ***********
    {
        id: 15,
        title : 'Budhas de la Meditación',
        description : "",
        options: ["Bronce", "Plata"],
        price : 2050,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/budhasmed.jpg',
        urlImgFrag: '',
    },
    {
        id: 16,
        title : 'Budhas Mini',
        description : "",
        options: ["Amarillo", "Rojo", "Lila", "Blanco", "Naranja", "Rosa", "Verde", "Celeste"],
        price : 950,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/budhasmini.jpg',
        urlImgFrag: '',
    },
    {
        id: 17,
        title : 'Cascada',
        description : "",
        options: [],
        price : 850,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/cascada.jpg',
        urlImgFrag: '',
    },
    {
        id: 18,
        title : 'Hornillo Corazón',
        description : "",
        options: ["Rosa", "Blanco", "Rojo"],
        price : 870,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/hornocoraz.jpg',
        urlImgFrag: '',
    },
    {
        id: 19,
        title : 'Hornillo Elefante',
        description : "",
        options: ["Negro", "Gris", "Blanco"],
        price : 1280,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/hornoelef.jpg',
        urlImgFrag: '',
    },
    {
        id: 20,
        title : 'Hornillo Hindú',
        description : "",
        options: ["Budha", "Elefante Ganesh"],
        price : 750,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/hornohindu.jpg',
        urlImgFrag: '',
    },
    {
        id: 21,
        title : 'Hornillo Pétalos',
        description : "",
        options: ["Blanco", "Gris", "Negro"],
        price : 580,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/hornopetalos.jpg',
        urlImgFrag: '',
    },
    {
        id: 22,
        title : 'Hornillo Rombo',
        description : "",
        options: ["Blanco", "Gris", "Marrón"],
        price : 860,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/hornorombo.jpg',
        urlImgFrag: '',
    },
    {
        id: 23,
        title : 'Lámpara Budha',
        description : "",
        options: ["No Veo", "No Escucho", "No Hablo"],
        price : 4300,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/lampbudha.jpg',
        urlImgFrag: '',
    },
    {
        id: 24,
        title : 'Lámpara Fenshui',
        description : "",
        options: ["Plata", "Bronce"],
        price : 4300,
        category:"decoracion",
        quantity: 1,
        urlImg: '/assets/productos/deco/lampfenshui.jpg',
        urlImgFrag: '',
    },

    // *********** CATEGORIA ILUMINARTE ***********
    {
        id: 25,
        title : 'Conos x 10',
        description : "",
        options: ["Champa","Energia Limpia","Esencias de la India","Frutilla",
                "Lavanda","Mango","Mil Flores","Palo Santo","jazmín","Rosa",
                "Sándalo","Vainilla"],
        price : 160,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/conos.jpg',
        urlImgFrag: '',
    },
    {
        id: 26,
        title : 'Sahumerios Variados x 20',
        description : "",
        options: [],
        price : 300,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/sahum.jpg',
        urlImgFrag: '',
    },
    {
        id: 27,
        title : 'Vela Mandala',
        description : "",
        options: ["Lavanda Francesa","Jazmín y Bamboo","Vainilla Africana"],
        price : 1200,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velamandala.jpg',
        urlImgFrag: '',
    },
    {
        id: 28,
        title : 'Velitas Blancas x 24',
        description : "",
        options: [],
        price : 1200,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velasblancas.jpg',
        urlImgFrag: '',
    },
    {
        id: 29,
        title : 'Velitas Colores x 12',
        description : "",
        options: ["Blancas","Rojas","Naranjas","Rosas","Azules","Violetas"],
        price : 450,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velascolor.jpg',
        urlImgFrag: '',
    },
    {
        id: 30,
        title : 'Vela de Soja',
        description : "",
        options: [],
        price : 1100,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velasoja.jpg',
        urlImgFrag: '',
    },
    {
        id: 31,
        title : 'Velitas Aromáticas x12 ',
        description : "",
        options: ["Citronela","Chocolate","Esencias de la India","Frutilla",
                "Lavanda","jazmín","Limón","Mango","Maracuyá","Pimpollo de Rosas",
                "Pomelo Naranja","Vainilla","Violeta"],
        price : 650,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velitasarom.jpg',
        urlImgFrag: '',
    },
    {
        id: 32,
        title : 'Velitas de Soja',
        description : "",
        options: [],
        price : 480,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/velitasoja.jpg',
        urlImgFrag: '',
    },
    {
        id: 33,
        title : 'Veloncitos',
        description : "",
        options: ["Citronela","Champa","Esencias de la India","Frutilla", "Flores de Violetas",
                "Lavanda","jazmín","Limón","Sándalo","Mango y Maracuyá","Pimpollo de Rosas",
                "Palo santo","Pomelo Naranja","Vainilla","Violeta", "Incienso"],
        price : 250,
        category:"iluminarte",
        quantity: 1,
        urlImg: '/assets/productos/iluminarte/veloncitos.jpg',
        urlImgFrag: '',
    },

]

export default listItems